using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Diagnostics;
using System.Collections.Generic;

namespace QuizOPoll.Models
{
    public class ApplicationUser : IdentityUser
    {
        public virtual ICollection<Quiz> Quizzes { get; set; }
        public virtual ICollection<Poll> Polls { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
        public virtual ICollection<Score> Scores { get; set; }

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;    
        }



    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection", throwIfV1Schema: false)
        {
            // Turn on logging of sql statements generated by EF
            Database.Log = sql => Debug.Write(sql); 
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}